#!/usr/bin/env bash
# This script changes the localhost and facebook.com ips.
cp /etc/hosts ~/n_hosts
sed -i "s/^127.0.0.1 localhost$//g" ~/n_hosts
echo 127.0.0.2 localhost >> ~/n_hosts
echo 8.8.8.8 facebook.com >> ~/n_hosts
cat ~/n_hosts > /etc/hosts
